# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.max_month: '%env(MAX_MONTH)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true
        bind:
            int $max_month: '%app.max_month%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        autowire: true
        public: false
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            # - '../src/Controller/'
            - '../src/Kernel.php'
            # - '../src/Command'

    App\EntityListener\:
        resource: "../src/EntityListener/"
        tags: ["doctrine.orm.entity_listener"]

    App\Service\Conversion:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true     
        arguments: 
            # - $logger : '@logger'
            - '%app.max_month%'
    
    # oscc.conversion:
    #     class: 'App\Service\Conversion'
    #     arguments: 
    #         # - $logger : '@logger'
    #         - $max_month : '%app.max_month%'


    oscc.generate:
        alias: 'App\Service\Generate'
           

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
